from django.db import models


class Word(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)


class User(models.Model):
    name = models.CharField(max_length=200, unique=True)
    score = models.IntegerField()


class Signs(models.Model):
    gesture = models.CharField(max_length=200, unique=True, primary_key=True)
    x0 = models.FloatField()
    x1 = models.FloatField()
    x2 = models.FloatField()
    x3 = models.FloatField()
    x4 = models.FloatField()
    x5 = models.FloatField()
    x6 = models.FloatField()
    x7 = models.FloatField()
    x8 = models.FloatField()
    x9 = models.FloatField()
    x10 = models.FloatField()
    x11 = models.FloatField()
    x12 = models.FloatField()
    x13 = models.FloatField()
    x14 = models.FloatField()
    x15 = models.FloatField()
    x16 = models.FloatField()
    x17 = models.FloatField()
    x18 = models.FloatField()
    x19 = models.FloatField()
    x20 = models.FloatField()
    y0 = models.FloatField()
    y1 = models.FloatField()
    y2 = models.FloatField()
    y3 = models.FloatField()
    y4 = models.FloatField()
    y5 = models.FloatField()
    y6 = models.FloatField()
    y7 = models.FloatField()
    y8 = models.FloatField()
    y9 = models.FloatField()
    y10 = models.FloatField()
    y11 = models.FloatField()
    y12 = models.FloatField()
    y13 = models.FloatField()
    y14 = models.FloatField()
    y15 = models.FloatField()
    y16 = models.FloatField()
    y17 = models.FloatField()
    y18 = models.FloatField()
    y19 = models.FloatField()
    y20 = models.FloatField()
    z0 = models.FloatField()
    z1 = models.FloatField()
    z2 = models.FloatField()
    z3 = models.FloatField()
    z4 = models.FloatField()
    z5 = models.FloatField()
    z6 = models.FloatField()
    z7 = models.FloatField()
    z8 = models.FloatField()
    z9 = models.FloatField()
    z10 = models.FloatField()
    z11 = models.FloatField()
    z12 = models.FloatField()
    z13 = models.FloatField()
    z14 = models.FloatField()
    z15 = models.FloatField()
    z16 = models.FloatField()
    z17 = models.FloatField()
    z18 = models.FloatField()
    z19 = models.FloatField()
    z20 = models.FloatField()
