# Generated by Django 4.0.5 on 2022-06-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrota', '0002_alter_user_id_alter_word_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(),
        ),
    ]
